### ISSUE TITLE
1.20 Update?

### ISSUE THREAD

**Issue by Riyuukii** [Kira-NT/packed-inventory#10]
When will 1.20 get released?

**Comment by Kira-NT** [comment]
Thank you for your interest in the project! Sadly, I cannot provide an ETA at this time. There's a lot happening in my life currently, including a move to new apartments. In addition, I need to work, support a larger project that other Minecraft developers rely on, and, as you might imagine, find some time to live life in between those tasks! :D

However, rest assured, I have not abandoned my mods, especially my beloved Packed Inventory. Even though I've developed larger and more complex mods, such as a Fabric port of the Sync mod, this one has proven to be the most useful for me as a player and it has entirely changed the way I interact with my inventory. But even with that in mind, mod development remains just a hobby of mine, so it isn't super prioritized on my to-do list. Despite that, I am hopeful that I will find time in the next few weeks to update all my mods to the latest MC version.
