### ISSUE TITLE
Incompatibility with Enchanted Shulkers (and any other mods that enchant shulker boxes)

### ISSUE THREAD

**Issue by Mnky313** [Kira-NT/packed-inventory#7]
If you enchant an empty shulker box, open it in your inventory with packed inventory and place items inside, then place it down the enchantments get cleared. (Same thing happens in reverse as well, if you add items to an enchanted shulker normally, then pick it up & remove all the items from it via packed inventory, then place it down it will also clear all enchantments.)

Tested on the latest version of Packed Inventory (0.2.2-1.19.1) on minecraft 1.19.2. (Enchanted Shulkers is version 4.0.1).

It also clears enchantments from other mods like Void Floating from the Enderite Mod.

**Comment by Kira-NT** [comment]
Yup, for some reason I didn't think about custom NBT-data that may be attached to a shulker box. Will be fixed in the next update
