### ISSUE TITLE
Update to 1.19.3 Please

### ISSUE THREAD

**Issue by sternschnaube** [Kira-NT/packed-inventory#8]
java.lang.NullPointerException: Cannot invoke "de.johni0702.minecraft.bobby.Bobby.getConfig()" because the return value of "de.johni0702.minecraft.bobby.Bobby.getInstance()" is null
	at Not Enough Crashes deobfuscated stack trace.(1.19.3+build.4)
	at net.minecraft.client.option.GameOptions.modify$zlp000$considerBobbyMaxRenderDistanceSetting(GameOptions:3181)
	at net.minecraft.client.option.GameOptions.<init>(GameOptions:1093)
	at net.minecraft.client.MinecraftClient.<init>(MinecraftClient:467)
	at net.minecraft.client.main.Main.main(Main:205)
	at net.minecraft.client.main.Main.main(Main:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

**Comment by Kira-NT** [comment]
Technically, the error message provided has nothing to do with my mod, it's about something called "Bobby", but yeah, sadly I haven't had a physical possibility to update all my mods to the latest 1.19.3 yet, however I definitely will do so

**Comment by venaminecraft** [comment]
Hello @Kir-Antipov, any update on this? 😊

**Comment by Kira-NT** [comment]
Sorry, it's taking me longer than expected. My primary focus is currently centered on another project (`mc-publish`), mods will be updated after I deal with it

**Comment by venaminecraft** [comment]
Thank you for the update @Kir-Antipov 🥳 
Doesn't matter how long it took - you've delivered for us.

There is already a ticket open which directs to a 1.20.x version. I would like to have a 1.20.2 version myself. 
Thanks!!

**Comment by Kira-NT** [comment]
Thank you so much for your kind words, they mean the world to me! I apologize for the delay anyways xD
I sure hope that at least 2024 will be a bit easier on apocalyptic events, so life struggles won't get in the way anymore. Also, I've made a few changes to the codebase of my mods to be able to react more promptly to new Minecraft updates. Thus, I do feel hopeful that the next update won't take a year or so for me to finally catch up with it xD

I'm currently working on `0.3.0+1.19.4` *(bug fixes, stability improvements, and a few more features)*. After that, Packed Inventory 0.3.0 will be ported to all 1.20.x releases. You can expect this to be finished in a few days :)

**Comment by venaminecraft** [comment]
I have to thank you, for your words.
Take all the time - I'm happy to hear that a 1.20.x version is planned 😊

**Comment by Kira-NT** [comment]
@sternschnaube, `0.3.0+1.20.2` has been published. Happy playing :)
